Fix mixed-indenting
Use double space indent

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

diff --git a/aqua-installer b/aqua-installer
--- a/aqua-installer
+++ b/aqua-installer
@@ -61,7 +61,7 @@ b9d657a6d64ae70ddf03c296a4563526dd34d2f911cf1b62a0a708aebab11b41  aqua_windows_a
 
 filename=aqua_${OS}_${ARCH}.tar.gz
 if [ "$OS" = windows ]; then
-	filename=aqua_${OS}_${ARCH}.zip
+  filename=aqua_${OS}_${ARCH}.zip
 fi
 URL=https://github.com/aquaproj/aqua/releases/download/$bootstrap_version/$filename
 
@@ -69,12 +69,12 @@ tempdir=$(mktemp -d)
 echo "[INFO] Installing aqua $bootstrap_version for bootstrapping..." >&2
 echo "[INFO] Downloading $URL ..." >&2
 if command -v curl > /dev/null 2>&1; then
-	curl --fail -L "$URL" -o "$tempdir/$filename"
+  curl --fail -L "$URL" -o "$tempdir/$filename"
 elif command -v wget > /dev/null 2>&1; then
-	wget -P "$tempdir" "$URL"
+  wget -P "$tempdir" "$URL"
 else
-	echo "[ERROR] Neither curl nor wget is found. Please install either curl or wget to download aqua" >&2
-	exit 1
+  echo "[ERROR] Neither curl nor wget is found. Please install either curl or wget to download aqua" >&2
+  exit 1
 fi
 
 cd "$tempdir"
@@ -85,21 +85,21 @@ if command -v sha256sum > /dev/null 2>&1; then
 elif command -v shasum > /dev/null 2>&1; then
   echo "$checksums" | grep "$filename" | shasum -a 256 -c
 else
-	echo "[WARN] Skipped checksum verification of aqua $bootstrap_version because both sha256sum and shasum commands aren't found" >&2
+  echo "[WARN] Skipped checksum verification of aqua $bootstrap_version because both sha256sum and shasum commands aren't found" >&2
 fi
 
 if [ "$OS" = windows ]; then
-	unzip "$filename" > /dev/null
+  unzip "$filename" > /dev/null
 else
-	tar xvzf "$filename" > /dev/null
+  tar xvzf "$filename" > /dev/null
 fi
 chmod a+x aqua
 if [ -n "${version:-}" ]; then
-	echo "[INFO] $tempdir/aqua update-aqua $version" >&2
-	./aqua update-aqua "$version"
+  echo "[INFO] $tempdir/aqua update-aqua $version" >&2
+  ./aqua update-aqua "$version"
 else
-	echo "[INFO] $tempdir/aqua update-aqua" >&2
-	./aqua update-aqua
+  echo "[INFO] $tempdir/aqua update-aqua" >&2
+  ./aqua update-aqua
 fi
 
 echo ""
@@ -109,7 +109,7 @@ echo '[INFO] Please add the path to the environment variable "PATH"' >&2
 # shellcheck disable=SC2016
 install_dir='${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin'
 if [ "$OS" = windows ]; then
-	# shellcheck disable=SC2016
+  # shellcheck disable=SC2016
   install_dir='${AQUA_ROOT_DIR:-$HOME/AppData/Local/aquaproj-aqua}/bin'
 fi
 echo "[INFO] export PATH=$install_dir:\$PATH" >&2
